# Generated by Django 5.1.4 on 2024-12-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_etiquette'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pid',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(choices=[('Davlat ekologik ekspertiza markazi', 'Davlat ekologik ekspertiza markazi'), ("Qoraqalpog'iston respublikasi filiali", "Qoraqalpog'iston respublikasi filiali"), ('Andijon viloyati filiali', 'Andijon viloyati filiali'), ('Buxoro viloyati filiali', 'Buxoro viloyati filiali'), ("Farg'ona viloyati filiali", "Farg'ona viloyati filiali"), ('Jizzax viloyati filiali', 'Jizzax viloyati filiali'), ('Qashqadaryo viloyati filiali', 'Qashqadaryo viloyati filiali'), ('Navoi viloyati filiali', 'Navoi viloyati filiali'), ('Namangan viloyati filiali', 'Namangan viloyati filiali'), ('Samarqand viloyati filiali', 'Samarqand viloyati filiali'), ('Surxondaryo viloyati filiali', 'Surxondaryo viloyati filiali'), ('Sirdaryo viloyati filiali', 'Sirdaryo viloyati filiali'), ('Toshkent viloyati filiali', 'Toshkent viloyati filiali'), ('Toshkent shahri filiali', 'Toshkent shahri filiali'), ('Xorazm viloyati filiali', 'Xorazm viloyati filiali')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Raxbariyat', 'Raxbariyat'), ('Ichki nazorat xizmati', 'Ichki nazorat xizmati'), ('Yuridik xizmati', 'Yuridik xizmati'), ("Buxgalteriya bo'limi", "Buxgalteriya bo'limi"), ("Birinchi bo'lim", "Birinchi bo'lim"), ('Inson resurslarini boshqarish', 'Inson resurslarini boshqarish'), ("Davlat tiliga rioya etilishini ta'minlash masalari", "Davlat tiliga rioya etilishini ta'minlash masalari"), ("Xo'jalik ishlari bo'limi", "Xo'jalik ishlari bo'limi"), ("Metodologiya bo'limi", "Metodologiya bo'limi"), ("Xalqaro konvensiyalar bilan ishlash bo'limi", "Xalqaro konvensiyalar bilan ishlash bo'limi"), ("Ijro intizomi bo'limi", "Ijro intizomi bo'limi"), ('Axborot kommunikatsiya texnologiyalarini rivojlantirish', 'Axborot kommunikatsiya texnologiyalarini rivojlantirish'), ("Jamoatchilik bilan ishlash bo'limi", "Jamoatchilik bilan ishlash bo'limi"), ("Davlat ekologik ekpertizasini o'tkazish boshqarmasi", "Davlat ekologik ekpertizasini o'tkazish boshqarmasi"), ("Davlat ekologik ekspertizasiga arizalarni qabul qilish bo'limi", "Davlat ekologik ekspertizasiga arizalarni qabul qilish bo'limi"), ("Ekologik ekspertiza obyektlarini to'yobga chiqarish bo'limi", "Ekologik ekspertiza obyektlarini to'yobga chiqarish bo'limi"), ("Axborot tahlil bo'limi", "Axborot tahlil bo'limi"), ("Monitoring bo'limi", "Monitoring bo'limi"), ("Texnik va xizmat ko'rsatish xodimlari", "Texnik va xizmat ko'rsatish xodimlari")], max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('Bosh direktor', 'Bosh direktor'), ("Bosh direktorning birinchi o'rinbosari", "Bosh direktorning birinchi o'rinbosari"), ("Bosh direktor o'ribosari", "Bosh direktor o'ribosari"), ('Bosh direktor maslahatchisi', 'Bosh direktor maslahatchisi'), ('Bosh yuriskonsult', 'Bosh yuriskonsult'), ("Bo'lim boshlig'i", "Bo'lim boshlig'i"), ('Bosh mutaxasis', 'Bosh mutaxasis'), ('Yetakchi mutaxasis', 'Yetakchi mutaxasis'), ('Texnik xodim', 'Texnik xodim'), ('Filial direktori', 'Filial direktori'), ('Hisobchi yetakchi mutaxasis', 'Hisobchi yetakchi mutaxasis'), ('Ekspert', 'Ekspert')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Mutaxasis axborot tahlil'), ('cadre', 'Mutaxasis kadr'), ('user', 'Xodim'), ('userx', 'XodimX')], max_length=100),
        ),
    ]
