# Generated by Django 5.1.4 on 2024-12-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_pid_alter_user_branch_alter_user_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created',
            field=models.DateField(),
        ),
    ]
