# Generated by Django 5.1.4 on 2024-12-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiquette',
            name='point',
            field=models.CharField(default=3, max_length=10),
        ),
    ]
