# Generated by Django 5.1.4 on 2024-12-19 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_etiquette_point'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='etiquette',
            name='unique_user_per_month',
        ),
        migrations.AlterUniqueTogether(
            name='etiquette',
            unique_together={('user', 'created')},
        ),
    ]
