# Generated by Django 5.1.4 on 2024-12-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_etiquette_unique_user_per_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiquette',
            name='created',
            field=models.DateField(),
        ),
    ]
