# Generated by Django 5.1.4 on 2024-12-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
